---
{{- if .Values.master.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multipaper.master.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multipaper.master.labels" . | nindent 4 }}
spec:
  type: {{ .Values.master.service.type }}
  ports:
    - port: {{ .Values.master.service.port }}
      targetPort: {{ .Values.master.service.port }}
  selector:
    {{- include "multipaper.selectorLabels.master" . | nindent 4 }}
---
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multipaper.master.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multipaper.master.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.master.replicaCount }}
  selector:
    matchLabels:
      {{- include "multipaper.selectorLabels.master" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.master.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "multipaper.selectorLabels.master" . | nindent 8 }}
    spec:
      {{- with .Values.master.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.master.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "multipaper.master.name" . }}
          securityContext:
            {{- toYaml .Values.master.securityContext | nindent 12 }}
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.master.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.master.service.port }}
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
      {{- with .Values.master.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
