---
apiVersion: v1
kind: Service
metadata:
  name: multipaper-master
  namespace: minecraft
spec:
  selector:
    instance: master
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 35353

---
apiVersion: v1
kind: Pod
metadata:
  name: multipaper-master
  namespace: minecraft
  labels:
    name: multipaper-master
    instance: master
spec:
  containers:
    - name: multipaper-master
      image: multipaper-master:latest
      imagePullPolicy: Never
      resources:
        limits:
          memory: 2048Mi
          cpu: 1000m
        requests:
          memory: 2048Mi
          cpu: 1000m
      ports:
        - containerPort: 35353
