---
apiVersion: v1
kind: Service
metadata:
  name: multipaper-primary
  namespace: minecraft
spec:
  selector:
    instance: primary
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 35353

---
apiVersion: v1
kind: Pod
metadata:
  name: multipaper-primary
  namespace: minecraft
  labels:
    name: multipaper-primary
    instance: primary
spec:
  containers:
    - name: multipaper-primary
      image: multipaper-primary:latest
      imagePullPolicy: Never
      resources:
        limits:
          memory: 2048Mi
          cpu: 1000m
        requests:
          memory: 2048Mi
          cpu: 1000m
      ports:
        - containerPort: 35353
