FROM amazoncorretto:17-al2023-jdk

EXPOSE 35353

ARG MULTIPAPER_MC_VERSION

ARG MULTIPAPER_BUILD_VERSION

WORKDIR /minecraft

ADD https://multipaper.io/api/v2/projects/multipaper/versions/${MULTIPAPER_MC_VERSION}/builds/${MULTIPAPER_BUILD_VERSION}/downloads/MultiPaper-Master-2.10.1-all.jar master.jar

ENTRYPOINT [ "java" ]

CMD [ "-Xmx1024M", "-Xms1024M", "-jar", "master.jar", "35353"]
