FROM amazoncorretto:17-al2023-jdk

EXPOSE 25565

ARG MPAPER_MC_VER

ARG MPAPER_BUID_VER

WORKDIR /minecraft

ADD https://multipaper.io/api/v2/projects/multipaper/versions/${MPAPER_MC_VER}/builds/${MPAPER_BUID_VER}/downloads/multipaper-${MPAPER_MC_VER}-${MPAPER_BUID_VER}.jar replica.jar

ENTRYPOINT [ "java" ]

CMD ["-Xmx1024M", "-Xms1024M", "-jar", "replica.jar", "nogui"]
