FROM amazoncorretto:17-al2023-jdk

EXPOSE 35353

ARG MPAPER_MC_VER

ARG MPAPER_BUID_VER

WORKDIR /minecraft

ADD https://multipaper.io/api/v2/projects/multipaper/versions/${MPAPER_MC_VER}/builds/${MPAPER_BUID_VER}/downloads/MultiPaper-Master-2.10.1-all.jar primary.jar

ENTRYPOINT [ "java" ]

CMD [ "-Xmx1024M", "-Xms1024M", "-jar", "primary.jar", "35353"]
