FROM amazoncorretto:17-al2023-jdk

EXPOSE 25565

ARG MULTIPAPER_MC_VERSION

ARG MULTIPAPER_BUILD_VERSION

WORKDIR /minecraft

ADD https://multipaper.io/api/v2/projects/multipaper/versions/${MULTIPAPER_MC_VERSION}/builds/${MULTIPAPER_BUILD_VERSION}/downloads/multipaper-${MULTIPAPER_MC_VERSION}-${MULTIPAPER_BUILD_VERSION}.jar worker.jar

ENTRYPOINT [ "java" ]

CMD ["-Xmx1024M", "-Xms1024M", "-jar", "worker.jar", "nogui"]
