---
apiVersion: v1
kind: Service
metadata:
  name: multipaper-master
  namespace: minecraft
spec:
  selector:
    instance: master
  ports:
    - name: master-tcp
      protocol: TCP
      port: 8080
      targetPort: 35353

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: multipaper-master
  namespace: minecraft
spec:
  selector:
    matchLabels:
      instance: master
  serviceName: multipaper-master
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        name: multipaper-master
        instance: master
    spec:
      containers:
        - name: multipaper-primary
          image: multipaper/master:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: 2048Mi
              cpu: 500m
            requests:
              memory: 1024Mi
              cpu: 250m
          ports:
            - containerPort: 35353
